// ---------------------------------------------------------------------------
// SPIDER-MAN PALETTE & ANIMATION FRAMES (Pixel-Art pur)
// ---------------------------------------------------------------------------

export const SPIDEY_PALETTE = {
    R: '#ef4444',
    r: '#b91c1c',
    U: '#2563eb',
    u: '#1d4ed8',
    W: '#ffffff',
    E: '#090d16',
};

export const SPIDEY_WALK_0 = [
    '.....rRRRRr.........',
    '....rRRRRRRr........',
    '...rRRWWRWWRr.......',
    '...rRREEREEEr.......',
    '....rRRRRRRr........',
    '.....rERRERr........',
    '...rRRERRERRr.......',
    '..rRRRERRERRRr......',
    '..rRRUUUUUURRr......',
    '..rRRUUUUUURRr......',
    '..rRRUUUUUURRr......',
    '...rRUUUUUURr.......',
    '.....UUUUUU.........',
    '.....UU..UU.........',
    '....UUU..UUU........',
    '....UU....UU........',
    '...rRR....rRR.......',
    '...rRR....rRR.......',
    '...rRR....rRR.......',
    '....................',
    '....................',
    '....................',
    '....................',
];

export const SPIDEY_WALK_1 = [
    '....................',
    '.....rRRRRr.........',
    '....rRRRRRRr........',
    '...rRRWWRWWRr.......',
    '...rRREEREEEr.......',
    '....rRRRRRRr........',
    '.....rERRERr........',
    '...rRRERRERRr.......',
    '..rRRRERRERRRr......',
    '..rRRUUUUUURRr......',
    '..rRRUUUUUURRr......',
    '...rRUUUUUURr.......',
    '.....UUUUUU.........',
    '......UUUU..........',
    '......UUUU..........',
    '.....rRRRRr.........',
    '.....rRRRRr.........',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
];

export const SPIDEY_WALK_2 = [
    '.....rRRRRr.........',
    '....rRRRRRRr........',
    '...rRRWWRWWRr.......',
    '...rRREEREEEr.......',
    '....rRRRRRRr........',
    '.....rERRERr........',
    '...rRRERRERRr.......',
    '..rRRRERRERRRr......',
    '..rRRUUUUUURRr......',
    '..rRRUUUUUURRr......',
    '..rRRUUUUUURRr......',
    '...rRUUUUUURr.......',
    '.....UUUUUU.........',
    '.....UU..UU.........',
    '....UU....UU........',
    '...UUU....UUU.......',
    '..rRR......rRR......',
    '..rRR......rRR......',
    '..rRR......rRR......',
    '....................',
    '....................',
    '....................',
    '....................',
];

export const SPIDEY_SHOOT = [
    '.....rRRRRr.........',
    '....rRRRRRRr........',
    '...rRRWWRWWRr.......',
    '...rRREEREEEr.......',
    '....rRRRRRRr...rRRW.',
    '.....rERRERr.rRRRRR.',
    '...rRRERRERRRRRRR...',
    '..rRRRERRERRr.......',
    '..rRRUUUUUURr.......',
    '..rRRUUUUUURr.......',
    '...rRUUUUUURr.......',
    '.....UUUUUU.........',
    '....UUUUUUUU........',
    '...UUU....UUU.......',
    '...UU......UU.......',
    '..rRR......rRR......',
    '..rRR......rRR......',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
];

export const SPIDEY_KO = [
    '....................',
    '.....rRRRRr.........',
    '....rRRRRRRr........',
    '...rRREEEEEEr.......',
    '...rRREEREEEr.......',
    '....rRRRRRRr........',
    '.....rERRERr........',
    '...rRRERRERRr.......',
    '..rRRRERRERRRr......',
    '..rRRUUUUUURRr......',
    '..rRRUUUUUURRr......',
    '...rRUUUUUURr.......',
    '.....UUUUUU.........',
    '......UUUU..........',
    '......UUUU..........',
    '.....rRRRRr.........',
    '.....rRRRRr.........',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
    '....................',
];

export const SPIDEY_FRAMES = [SPIDEY_WALK_0, SPIDEY_WALK_1, SPIDEY_WALK_2, SPIDEY_WALK_1];
