services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pierre_portfolio
    restart: unless-stopped
    ports:
      - "${PORT:-3006}:5001"
    env_file:
      - path: ./.env.local
        required: false
      - path: ./.env
        required: false
    environment:
      - NODE_ENV=production
      - API_PORT=5001
